# Generated by Django 6.0 on 2025-12-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='created_at',
            new_name='requested_at',
        ),
        migrations.AddField(
            model_name='delivery',
            name='estimated_time_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='pending', max_length=30),
        ),
    ]
